/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AppointmentRow
 */
export interface AppointmentRow {
    /**
     * 
     * @type {string}
     * @memberof AppointmentRow
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRow
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRow
     */
    'client'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRow
     */
    'created'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AppointmentRow
     */
    'homeowner'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRow
     */
    'region'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRow
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRow
     */
    'stage'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRow
     */
    'zip'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRow
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRow
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRow
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRow
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRow
     */
    'appointmentDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRow
     */
    'appointmentTime'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AppointmentRow
     */
    'success'?: boolean;
}

