/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AppointmentRequest
 */
export interface AppointmentRequest {
    /**
     * 
     * @type {string}
     * @memberof AppointmentRequest
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRequest
     */
    'slotId': string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRequest
     */
    'date': string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRequest
     */
    'time': string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRequest
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRequest
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRequest
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRequest
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRequest
     */
    'zip'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRequest
     */
    'comments'?: string;
}

