/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AppointmentStep
 */
export interface AppointmentStep {
    /**
     * 
     * @type {string}
     * @memberof AppointmentStep
     */
    'updated'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentStep
     */
    'path'?: string;
    /**
     * 
     * @type {{ [key: string]: any | undefined; }}
     * @memberof AppointmentStep
     */
    'properties'?: { [key: string]: any | undefined; };
}

