/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ErrorRow
 */
export interface ErrorRow {
    /**
     * 
     * @type {string}
     * @memberof ErrorRow
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorRow
     */
    'client'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorRow
     */
    'path'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorRow
     */
    'ip'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorRow
     */
    'timestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorRow
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorRow
     */
    'status'?: number;
}

