/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TimeSlot } from './time-slot';

/**
 * 
 * @export
 * @interface ProposedAppointment
 */
export interface ProposedAppointment {
    /**
     * 
     * @type {string}
     * @memberof ProposedAppointment
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProposedAppointment
     */
    'appointmentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProposedAppointment
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProposedAppointment
     */
    'time'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProposedAppointment
     */
    'prospectId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProposedAppointment
     */
    'slotId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProposedAppointment
     */
    'region'?: string;
    /**
     * 
     * @type {Array<TimeSlot>}
     * @memberof ProposedAppointment
     */
    'timeSlots'?: Array<TimeSlot>;
}

