/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProspectRequest
 */
export interface ProspectRequest {
    /**
     * 
     * @type {string}
     * @memberof ProspectRequest
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof ProspectRequest
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof ProspectRequest
     */
    'zip': string;
    /**
     * 
     * @type {string}
     * @memberof ProspectRequest
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectRequest
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectRequest
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectRequest
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectRequest
     */
    'phone'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProspectRequest
     */
    'homeowner'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProspectRequest
     */
    'contact'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProspectRequest
     */
    'notes'?: string;
}

