/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RequestDetail
 */
export interface RequestDetail {
    /**
     * 
     * @type {string}
     * @memberof RequestDetail
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestDetail
     */
    'client'?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestDetail
     */
    'ip'?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestDetail
     */
    'origin'?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestDetail
     */
    'path'?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestDetail
     */
    'timestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestDetail
     */
    'requestId'?: string;
    /**
     * 
     * @type {{ [key: string]: string | undefined; }}
     * @memberof RequestDetail
     */
    'headers'?: { [key: string]: string | undefined; };
    /**
     * 
     * @type {{ [key: string]: string | undefined; }}
     * @memberof RequestDetail
     */
    'params'?: { [key: string]: string | undefined; };
}

