/* tslint:disable */
/* eslint-disable */
/**
 * Scheduler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ScheduledAppointment
 */
export interface ScheduledAppointment {
    /**
     * 
     * @type {string}
     * @memberof ScheduledAppointment
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduledAppointment
     */
    'appointmentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduledAppointment
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduledAppointment
     */
    'time'?: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduledAppointment
     */
    'prospectId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduledAppointment
     */
    'slotId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduledAppointment
     */
    'region'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ScheduledAppointment
     */
    'success'?: boolean;
}

